name: Dependabot Notify

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify via Slack
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\": \"A PR was merged successfully into the main branch!\\n\\n*PR Title:* $PR_TITLE\\n*PR URL:* $PR_URL\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
