name: Dependabot Notify

on:
  push:
    branches:
      - main  # or specify another branch if you want

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Push Event
        run: echo "Push event triggered!"
