name: Dependabot Notify

on:
  pull_request:
    types:
      - closed

jobs:
  notify:
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo " A Dependabot PR was merged successfully!"
