name: Build and Submit with Expo EAS

on:
  push:
    branches: [main]  # You can change this to any branch you want

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Set Expo Token
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      - name: Build Android APK (Non-Prod)
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build iOS ADHOC IPA (Non-Prod)
        run: eas build --platform ios --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-android-apk
          path: '**/*.apk'

      - name: Upload iOS IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-ios-ipa
          path: '**/*.ipa'

  submit:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: expo-android-apk
          path: ./android

      - name: Download iOS IPA
        uses: actions/download-artifact@v4
        with:
          name: expo-ios-ipa
          path: ./ios

      - name: List Downloaded Files (Debug)
        run: |
          echo "APK files:"
          ls -al ./android
          echo "IPA files:"
          ls -al ./ios

      - name: Submit Android APK to Google Play
        run: eas submit --platform android --path ./android/your-app.apk --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Submit iOS IPA to App Store
        run: eas submit --platform ios --path ./ios/your-app.ipa --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Dependabot (npm)
        uses: actions/github-script@v7
        with:
          script: |
            console.log("Dependabot runs automatically via GitHub UI. No manual trigger needed.")
