name: Build and Submit with Expo EAS

on:
  workflow_dispatch:
    inputs:
      run_qa_build:
        description: 'Run QA Build?'
        required: true
        default: 'true'
        type: boolean
      run_production_build:
        description: 'Run Production Build?'
        required: true
        default: 'false'
        type: boolean
      submit_to_play_store:
        description: 'Submit to Google Play?'
        required: true
        default: 'false'
        type: boolean

jobs:
  # Job for QA Build (Android and iOS Preview Builds)
  qa-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_qa_build == 'true' }}  # Run this job only if 'run_qa_build' is true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Set Expo Token
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      # Preview APK build (for internal testing)
      - name: Build Android APK (Preview)
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Preview IPA build (for iOS)
      - name: Build iOS IPA (Preview)
        run: eas build --platform ios --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        continue-on-error: true  # Skip if iOS credentials are missing

  # Job for Production Build (Android AAB for Play Store and iOS IPA for App Store)
  production-build:
    runs-on: ubuntu-latest
    needs: qa-build  # Ensure production build runs after the QA build completes
    if: ${{ github.event.inputs.run_production_build == 'true' }}  # Run this job only if 'run_production_build' is true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Set Expo Token
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      # Production Android AAB build (for Play Store)
      - name: Build Android AAB (Production)
        run: eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Production iOS IPA build (for App Store)
      - name: Build iOS IPA (Production)
        run: eas build --platform ios --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        continue-on-error: true  # Skip if iOS credentials are missing

  # Job for Submission (Submits the builds to the relevant stores)
  submit:
    runs-on: ubuntu-latest
    needs: production-build  # Ensure submission happens after production build
    if: ${{ github.event.inputs.submit_to_play_store == 'true' }}  # Run this job only if 'submit_to_play_store' is true

    steps:
      # Checkout the latest code again for the submit job
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies (required if any submission script needs them)
      - name: Install dependencies
        run: npm install

      # Install EAS CLI globally
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Submit Android AAB to Google Play
      - name: Submit Android AAB to Google Play
        run: eas submit --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Optional iOS submission
      - name: Submit iOS IPA to App Store
        if: always()
        run: eas submit --platform ios --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  dependabot:
    runs-on: ubuntu-latest
    needs: [production-build, submit]  # Dependabot runs only after production build and submission
    if: ${{ github.event.inputs.submit_to_play_store == 'true' }}  # Adjust this condition as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Dependabot (npm)
        uses: actions/github-script@v7
        with:
          script: |
            console.log("Dependabot runs automatically via GitHub UI. No manual trigger needed.")
