name: Build and Submit with Expo EAS

on:
  push:
    branches: [main]  # Trigger the workflow when code is pushed to the main branch (adjust as needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Set Expo Token
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      # Build Android AAB (Production Build)
      - name: Build Android AAB
        run: eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Build iOS IPA (Production Build)
      - name: Build iOS IPA
        run: eas build --platform ios --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        continue-on-error: true  # Continue even if iOS build fails (because it requires Apple credentials)

  submit:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job completes

    steps:
      # Checkout the latest code again for the submit job
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies (required if any submission script needs them)
      - name: Install dependencies
        run: npm install

      # Install EAS CLI globally
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Submit Android AAB to Google Play Store
      - name: Submit Android AAB to Google Play
        run: |
          # Ensure the build file is present and submit it
          eas submit --platform android --non-interactive --archive /home/expo/workingdir/build/android/app/build/outputs/bundle/release/app-release.aab
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Submit iOS build to App Store (optional, will work only if Apple credentials are set)
      - name: Submit iOS IPA to App Store
        if: always()
        run: |
          eas submit --platform ios --non-interactive --archive ./dist/my-app.ipa
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Dependabot (npm)
        uses: actions/github-script@v7
        with:
          script: |
            console.log("Dependabot runs automatically via GitHub UI. No manual trigger needed.")
