name: Build and Submit with Expo EAS

on:
  push:
    branches: [main]  # Trigger the workflow when code is pushed to the main branch (adjust as needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Set Expo Token for authentication with Expo servers
      - name: Set Expo Token
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      # Build Android APK (Preview Build) for internal testing (using Preview profile)
      - name: Build Android APK (Preview)
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Build Android AAB (Production Build) for Google Play
      - name: Build Android AAB (Production)
        run: eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Build iOS IPA (Preview Build) — using the "preview" profile
      - name: Build iOS IPA (Preview)
        run: eas build --platform ios --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        continue-on-error: true  # Skip if credentials are not available for iOS

  submit:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job completes

    steps:
      # Checkout the latest code again for the submit job
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies (required if any submission script needs them)
      - name: Install dependencies
        run: npm install

      # Install EAS CLI globally
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Submit Android AAB to Google Play (no need for --archive argument)
      - name: Submit Android AAB to Google Play
        run: eas submit --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Optional iOS submission — will only work if credentials are set
      - name: Submit iOS IPA to App Store
        if: always()
        run: eas submit --platform ios --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Dependabot (npm)
        uses: actions/github-script@v7
        with:
          script: |
            console.log("Dependabot runs automatically via GitHub UI. No manual trigger needed.")
