name: Build and Submit with Expo EAS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Set Expo Token
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      - name: Build Android APK (Non-Prod)
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # iOS build included but will fail if Apple credentials not set
      - name: Build iOS ADHOC IPA (Non-Prod)
        run: eas build --platform ios --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        continue-on-error: true  # Let the build continue even if iOS fails

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-android-apk
          path: android/app/build/outputs/apk/release/app-release.apk

  submit:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: expo-android-apk
          path: ./android

      - name: List Downloaded APK
        run: ls -al ./android

      - name: Submit Android APK to Google Play
        run: eas submit --platform android --path ./android/app-release.apk --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # iOS IPA download and submission (optional, won't work unless credentials are set)
      - name: Download iOS IPA
        if: always()  # Always attempt
        uses: actions/download-artifact@v4
        with:
          name: expo-ios-ipa
          path: ./ios

      - name: Submit iOS IPA to App Store
        if: always()
        run: |
          if [ -f "./ios/your-app.ipa" ]; then
            eas submit --platform ios --path ./ios/your-app.ipa --non-interactive
          else
            echo "Skipping iOS submit: IPA not found or iOS build failed."
          fi
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Dependabot (npm)
        uses: actions/github-script@v7
        with:
          script: |
            console.log("Dependabot runs automatically via GitHub UI.")
