name: Expo Build for Android and iOS

on:
  push:
    branches:
      - main  # This will trigger the build on every push to the main branch
  pull_request:
    branches:
      - main  # This will trigger the build on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # You can use the Node version that works for your project

    - name: Install dependencies
      run: npm install

    - name: Log in to Expo
      run: |
        echo "//expo.dev/token=${{ secrets.EXPO_TOKEN }}" > ~/.npmrc

    - name: Build Android APK
      run: |
        npx eas build --platform android --non-interactive

    - name: Build iOS IPA
      run: |
        npx eas build --platform ios --non-interactive

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: expo-builds
        path: |
          **/*.apk
          **/*.ipa
