name: Build Android with Expo EAS

on:
  push:
    branches: [main]  # You can change this to any branch you want

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Or match your project's Node version

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Set Expo Token for authentication
        run: |
          echo ${{ secrets.EXPO_TOKEN }} > ~/.expo/token
          cat ~/.expo/token

      - name: Build Android app
        run: eas build --platform android --non-interactive

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: expo-builds
          path: |
            **/*.apk
