name: Build and Submit with Expo EAS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Set Expo Token
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      - name: Build Android APK (Non-Prod)
        id: android_build
        run: |
          eas build --platform android --profile preview --non-interactive --json > android-build.json
          cat android-build.json
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download Android APK
        run: |
          APK_URL=$(cat android-build.json | jq -r '.artifacts.buildUrl')
          curl -o app.apk "$APK_URL"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-android-apk
          path: app.apk

      # OPTIONAL - skip iOS if you don’t have credentials
      # Or keep iOS block if you add creds later

  submit:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: expo-android-apk
          path: ./android

      - name: List APKs
        run: ls -al ./android

      - name: Submit Android APK to Google Play
        run: eas submit --platform android --path ./android/app.apk --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Dependabot (npm)
        uses: actions/github-script@v7
        with:
          script: |
            console.log("Dependabot runs automatically via GitHub UI. No manuals trigger needed.")
