name: Build and Submit with Expo EAS

on:
  push:
    branches: [main]  # Trigger the workflow when code is pushed to the main branch (adjust as needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Set Expo Token
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      # Build Android APK (Non-Prod)
      - name: Build Android APK
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Build iOS IPA (Non-Prod)
      - name: Build iOS IPA
        run: eas build --platform ios --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        continue-on-error: true  # Continue even if iOS build fails (because it requires Apple credentials)

  submit:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job completes successfully

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Submit Android APK to Google Play
      - name: Submit Android APK to Google Play
        run: |
          eas submit --platform android --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Submit iOS IPA to App Store (optional, will only work if Apple credentials are set)
      - name: Submit iOS IPA to App Store
        if: always()  # Always attempt to submit iOS IPA, even if previous steps fail
        run: |
          eas submit --platform ios --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Dependabot (npm)
        uses: actions/github-script@v7
        with:
          script: |
            console.log("Dependabot runs automatically via GitHub UI. No manual trigger needed.")
